### ISSUE TITLE
Add missing front end tests for single, multi and all records components.

### ISSUE THREAD

**Issue by awalkowiak** [benetech/ServiceNet#861] opened 2020-03-05 12:08 UTC
This is related to service: ServiceNetGateway.

Add missing jest tests for SingleRecordView, MultipleRecordView, AllRecordsView components.

**Comment by kdondziak** [comment] 2020-08-18 12:46
@johnhbenetech It is related to old view. Should we create task for new views?

**Comment by johnhbenetech** [comment] 2020-08-18 12:54
@kdondziak yes please do

**Comment by johnhbenetech** [comment] 2020-08-28 21:56
Is #1151 a duplicate of this? If so feel free to close it.

**Closed** 2020-09-02 11:54 UTC
Labels: Story Points: 5, estimated, tech-debt-ideas
