### ISSUE TITLE
CBO/ORG add a new record option to specify if it's an online or remote service

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1321] opened 2020-10-15 17:42 UTC
Purpose
------
Provide SP to specify if their services are offered completely online (remotely) or also, offered online on top of having a location

Users
-----------
Service Providers

Features
-----------
- On the locations tab of all records, editing, adding a new record, add a toggle button which says "Do you offer only online Services?" and then a toggle as the mockup shows 
- If the user toggles to yes, have a new panel populate asking where the headquarters are at (don't make the fields required and remove the red asterisk on mockup)
- If the user toggles no, keep the current layout under Locations and simply add a checkbox in the bottom that the service is also offered online /remote - "This location also offers online/remote services"

Mockups
-----------
_Desktop_
------
<img width="639" alt="Screenshot 2020-12-15 112330" src="https://user-images.githubusercontent.com/65787629/102262470-000a7a00-3ec8-11eb-8530-c669a37d6aab.png">

<img width="641" alt="Screenshot 2020-12-15 112400" src="https://user-images.githubusercontent.com/65787629/102262503-0c8ed280-3ec8-11eb-8c8c-4127f346f4ea.png">

_Mobile_
------
<img width="160" alt="Screenshot 2020-12-15 113116" src="https://user-images.githubusercontent.com/65787629/102263385-16fd9c00-3ec9-11eb-9c42-a25e52372b77.png">
<img width="167" alt="Screenshot 2020-12-15 113128" src="https://user-images.githubusercontent.com/65787629/102263386-17963280-3ec9-11eb-9b4a-5af8f0fdd0aa.png">

- only show this label in a single record view if either one or all services are offered online 

<img width="881" alt="Screenshot 2021-01-22 074848" src="https://user-images.githubusercontent.com/65787629/105512714-4fda1f00-5c86-11eb-8cab-8601b8762607.png">
<img width="174" alt="Screenshot 2021-01-22 074859" src="https://user-images.githubusercontent.com/65787629/105512717-4fda1f00-5c86-11eb-949d-a8c6dc5c4e92.png">

**Comment by EnriqueCorado** [comment] 2020-10-15 18:07
@johnhbenetech thoughts?

**Comment by johnhbenetech** [comment] 2020-10-15 20:09
This makes sense to me @EnriqueCorado - the only consideration is that these wont appear on the map obviously and if someone has a geo filter (city, zip, etc) it would also never show. What do you think?

**Comment by EnriqueCorado** [comment] 2020-10-15 20:14
@johnhbenetech 

Great point; I will add a box where the user can fill out which specific area (city or county) they operate in and/or a general area, for example, the "bay area" option

**Comment by EnriqueCorado** [comment] 2020-10-15 20:36
<img width="827" alt="Screenshot 2020-10-15 132430" src="https://user-images.githubusercontent.com/65787629/96182058-c6c68580-0ee9-11eb-8253-6c5af1cbeb15.png">

if service offered strictly online, the user must specify at least one filter of where they operate in 
<img width="834" alt="Screenshot 2020-10-15 132523" src="https://user-images.githubusercontent.com/65787629/96182147-e493ea80-0ee9-11eb-979d-b548d95756ed.png">

**Comment by johnhbenetech** [comment] 2020-11-02 18:49
@EnriqueCorado Any thoughts about if the service is virtual but website is blank? What should we display in the location card?

**Comment by EnriqueCorado** [comment] 2020-11-02 19:27
@johnhbenetech 

We can have automated options for different cases:

Case #1 There exists a phone number, email, but no website 
Option 1: Add emphasis on the phone number, bolded
Option 2: simply add a fill-in text that says "Please call for more information regarding this virtual service" + "Please email ___@__.com for more information for this virtual service"
**Option 2 is the best**

Casse #2: If no website, no phone number, but provided an email 
In the description add "Please email ___@__.com for more information regarding this virtual service"

Case #3: No number, email, website
Option 1: The record should be in a hidden state since it defeats the purpose of service net up to date information 
Option 2: Could say something along the lines of google the org name, but it is very unprofessional 
**option 1**

**Comment by kdondziak** [comment] 2021-01-11 09:19
@EnriqueCorado If "Do you offer only online Services" is toggled (yes), should the user be able to add another location?

**Comment by kdondziak** [comment] 2021-01-11 13:55
@EnriqueCorado If "Do you offer only online Services" is toggled (yes), should the user be able to add another location?

**Comment by EnriqueCorado** [comment] 2021-01-11 15:22
@kdondziak no, theres the toggle button to state that the service is completely online and there's a check box after the location if the org also offers an online service

**Comment by kdondziak** [comment] 2021-01-18 11:34
@EnriqueCorado Should this section be on the 'headquarter' form?
![image](https://user-images.githubusercontent.com/52406204/104910346-7992fd80-5989-11eb-9c83-2cbf959d0721.png)

**Comment by kdondziak** [comment] 2021-01-18 14:50
@EnriqueCorado Can you also tell me where should "Do you offer only online Services" checkbox be placed on the edit page?

**Comment by EnriqueCorado** [comment] 2021-01-18 16:18
@kdondziak please add the section to the 'headquarter' form 
- 
<img width="900" alt="Screenshot 2021-01-18 081753" src="https://user-images.githubusercontent.com/65787629/104939757-acc39580-5965-11eb-83e0-d60ca8f29fd9.png">

**Comment by kdondziak** [comment] 2021-01-19 14:07
@EnriqueCorado Should the location remote field be visible on the single record page? If yes can you give some mockup?
![image](https://user-images.githubusercontent.com/52406204/105045266-06ac8400-5a68-11eb-9626-b52ef4d5a39a.png)

**Comment by EnriqueCorado** [comment] 2021-01-19 15:46
@kdondziak yes!

- always show if services offered online first, then below the 24/7 checkbox 
- if the service is 24/7 and not offered online then keep the check box at the top right as you have 
thanks!

<img width="900" alt="Screenshot 2021-01-19 074202" src="https://user-images.githubusercontent.com/65787629/105057381-05f4fd00-5a2a-11eb-98a3-392b5ad03bdd.png">

<img width="263" alt="Screenshot 2021-01-19 074606" src="https://user-images.githubusercontent.com/65787629/105057794-6dab4800-5a2a-11eb-88b9-1c33380ca725.png">

**Comment by kdondziak** [comment] 2021-01-22 11:34
@EnriqueCorado Can you add a mockup of how to visualize that "Do you offer only online Services?" is true on the single record view?

**Comment by EnriqueCorado** [comment] 2021-01-22 15:49
@kdondziak 
- only show this label in a single record view if either one or all services are offered online 

<img width="881" alt="Screenshot 2021-01-22 074848" src="https://user-images.githubusercontent.com/65787629/105512714-4fda1f00-5c86-11eb-8cab-8601b8762607.png">
<img width="174" alt="Screenshot 2021-01-22 074859" src="https://user-images.githubusercontent.com/65787629/105512717-4fda1f00-5c86-11eb-949d-a8c6dc5c4e92.png">

**Comment by abaranowska1** [comment] 2021-01-26 15:16
Going through the description and all comments and found some things that need to be fixed or I had questions:

1. @kdondziak @EnriqueCorado 
I think about this new functionality and I understand that after mark Checkbox "Do you offer only online Services?" we are moved to the first location and we can edit the main company address but in this situation, the second, third location are removed. Shouldn't we bring back other locations after unmark checkbox? 
![Peek 2021-01-26 15-42](https://user-images.githubusercontent.com/61964176/105862720-666ad800-5ff0-11eb-87b7-ed077a3bfff3.gif)
2. There is a chance to remove all locations, but when we go back to the edit mode one location is displayed.
![Peek 2021-01-26 15-43](https://user-images.githubusercontent.com/61964176/105863023-be094380-5ff0-11eb-9781-2e8f8cbe7422.gif)
3. Also I recorded one situation when the  Checkbox "Do you offer only online Services?" = true , but two locations are displayed. It is hard to reproduce it, but maybe you will find something in code. 
![Peek 2021-01-26 15-00](https://user-images.githubusercontent.com/61964176/105863393-23f5cb00-5ff1-11eb-8703-50812ab8d670.gif)

**Comment by EnriqueCorado** [comment] 2021-01-26 16:06
@abaranowska1 @kdondziak 
1. yes, bring back the second and third locations. We want the user to be able to add another location for non-online services/services also offered online 
2. Goal is to be able to tie a service to its location whether it is offered online or has a location or has a location and also offer online services

**Comment by kdondziak** [comment] 2021-01-27 15:49
@abaranowska1 
Point 1: will be fixed soon.
Point 2: The location that you have seen is an empty template for adding a new location in case there is no location in the edited organization. I have not changed this.
Point 3: Unfortunately I can't reproduce this. We need to observe this to find a way to narrow it.

**Comment by EnriqueCorado** [comment] 2021-01-28 17:45
creating new records, clicking on "Do you only offer online services" defaulting state to CA
- please add a condition when a user clicks on "Do you only offer online services" to not set a default state to any state, leave it blank unless state picked by user

<img width="674" alt="Screenshot 2021-01-28 094136" src="https://user-images.githubusercontent.com/65787629/106177377-4ac91400-614d-11eb-80bf-8efe37726340.png">
<img width="953" alt="Screenshot 2021-01-28 094057" src="https://user-images.githubusercontent.com/65787629/106177378-4b61aa80-614d-11eb-9b9d-7e01154f4e99.png">

**Comment by abaranowska1** [comment] 2021-01-29 12:22
**Tested**
@EnriqueCorado 
1. After unmark the Checkbox "Do you offer only online Services?" for the Organization with more than one location it is possible to see more than 1 in the edit mode. After we save the changes it is not possible to bring back previous locations, is it okay for you ? 
![Peek 2021-01-29 13-00](https://user-images.githubusercontent.com/61964176/106273104-63f7c080-6232-11eb-893e-061a7a197a01.gif)

- case related to deleting location for the referred organization will be handle in #1675 
- there is a chance to delete all locations from the Organization 
- two checkboxes were added to the create/edit view
@kdondziak @EnriqueCorado What is the final decision about who it (single record view) looks like, I saw 2 different mockups, please update the description.
- single record view now
-- Web: 
![Selection_987](https://user-images.githubusercontent.com/61964176/106274506-a91cf200-6234-11eb-9a2c-f4eba49e482e.png)
-- Mobile View: 
![Selection_986](https://user-images.githubusercontent.com/61964176/106274515-acb07900-6234-11eb-93d2-04ce25565c2c.png)
![Selection_985](https://user-images.githubusercontent.com/61964176/106274534-b4701d80-6234-11eb-968c-07d079589aeb.png)

**Comment by EnriqueCorado** [comment] 2021-01-29 16:01
@abaranowska1 updated description. mock up under  only show this label in a single record view if either one or all services are offered online

1. After unmark the Checkbox "Do you offer only online Services?" for the Organization with more than one location it is possible to see more than 1 in the edit mode. After we save the changes it is not possible to bring back previous locations, is it okay for you ?
- that is fine

**Comment by abaranowska1** [comment] 2021-02-01 07:40
@kdondziak please change the single record view if either one or all services are offered online, mock ups are in the updated description

**Comment by abaranowska1** [comment] 2021-02-03 11:08
@kdondziak I cannot see the last changes.

**Comment by kdondziak** [comment] 2021-02-04 08:51
@EnriqueCorado 
Should this label be displayed on 'your records'?
![image_2021_02_04T08_48_15_103Z](https://user-images.githubusercontent.com/52406204/106867915-7197c500-66ce-11eb-8241-810cd2ca2972.png)

**Comment by abaranowska1** [comment] 2021-02-04 08:57
@kdondziak 
1. Plz fix displaying long Organization Names on cards
![Selection_999(027)](https://user-images.githubusercontent.com/61964176/106868520-26ca7d00-66cf-11eb-857f-7c8f838c1492.png)

2. I think that the font should be a little smaller, not 16px but 14px .

**Comment by EnriqueCorado** [comment] 2021-02-04 15:42
@kdondziak yes, display on owned records as well

**Comment by abaranowska1** [comment] 2021-02-05 12:49
**Tested with success**
Last changes to this feature were made. All records view :
![image](https://user-images.githubusercontent.com/61964176/107033767-0fb28a80-67b6-11eb-8981-e39f79f100bf.png)
![image](https://user-images.githubusercontent.com/61964176/107033753-09bca980-67b6-11eb-8337-cfa7fc93aa88.png)

**Closed** 2021-02-10 15:26 UTC
Labels: Story Points: 2, estimated
