### ISSUE TITLE
Come up with proper approach for populating taxonomy filter dropdown

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#623] opened 2019-08-08 18:44 UTC
So this is my current understanding of how taxonomy filter dropdown is populated:

* Taxonomies are pulled from various partner systems, either through pulling values from CSV uploads, or by hitting specific taxonomy API 

* The dropdown then shows all taxonomies from all partners

So this can get complicated for a few reasons:

1. There exist taxonomies in the dropdown that have no records associated with them (they are simply available through the API endpoint). This can be confusing when a user repeated runs into issues where no records are returned.

2. As we've discussed previously, the complexity increases with the 'only show matching' off. If you select a taxonomy from a partner system, none of your records will return. If you pick a taxonomy from your system, no partner records will return.

@NeilMBenetech what's the recommended path forward here? Maybe for 1 we simply dont show values that have no records associated with them.

Number 2 is daunting and gets at the need for the rosetta stone concept. How do you think we should progress here?

**Comment by johnhbenetech** [comment] 2019-08-09 11:45
yes

________________________________

**Comment by NeilMBenetech** [comment] 2019-08-29 16:19
@johnhbenetech I think the only way to solve this is via the Taxonomy Rosetta Stone. https://github.com/benetech/ServiceNet/issues/319 

It is an important issue and for the reasons you note above, it can cause confusion for our users leading to less trust in the system.

**Comment by NeilMBenetech** [comment] 2019-08-29 16:37
@johnhbenetech Oh and absolutely, we should not show taxonomy terms in the auto-suggest / filter that do not have any records associated with them. 

It would be ideal if the other filters could also be applied to what gets autosuggested in the taxonomy filter. For example "There are no Food Pantries in Marin County" so don't auto-suggest Food Pantries when Marin County is in the geo filter...and so on. This is probably pretty challenging though so feel free to decline at this time.

**Comment by bognasoldev89** [comment] 2019-10-17 14:47
At this moment the dropdown list is populated for other providers, not the one that user is logged. I think it needs a little more work.

Here example of how it works right now:
![Peek 2019-10-17 16-44](https://user-images.githubusercontent.com/51324797/67019901-a8268680-f0fd-11e9-92dd-85aa8daab332.gif)

**Comment by NeilMBenetech** [comment] 2019-10-25 19:56
@bognasoldev89 Yes, it should autosuggest the taxonomy of the current user, when no particular partner data source is selected.

**Comment by NeilMBenetech** [comment] 2019-11-14 22:18
@bognasoldev89 @johnhbenetech Just tried this in Staging logged in as a UWBA user and I get zero autosuggested taxonomy terms when I typed: Food . Of course I should get at least a few such terms.

**Comment by bognasoldev89** [comment] 2019-11-20 14:34
@NeilMBenetech @johnhbenetech I suppose that lack of results of auto-suggested taxonomies was because of #730 and now autosuggest works.
But still, there's something wrong with actual filtering records by taxonomies. I only got hits for ShelterTech and healthleads providers, and not for every chosen taxonomy.
@jkondrat can you please investigate further?

**Comment by bognasoldev89** [comment] 2019-12-03 16:40
I can confirm that Taxonomy filter works great and I always got hits for randomly chosen filters for ShelterTech, LAAC and healthleads, just like that:

![st taxonomy](https://user-images.githubusercontent.com/51324797/70070307-ad7b5a00-15f3-11ea-8fde-e88f18841184.gif)

But for Eden, UWBA and SMC Taxonomy filter dropdown is empty:

![eden taxonomy](https://user-images.githubusercontent.com/51324797/70070351-c126c080-15f3-11ea-904f-1aa478dc4248.gif)

![smc taxonomy](https://user-images.githubusercontent.com/51324797/70070354-c126c080-15f3-11ea-85e0-a39af9b7735c.gif)

![uwba taxonomy](https://user-images.githubusercontent.com/51324797/70070356-c1bf5700-15f3-11ea-915b-6d0cd7bf53eb.gif)

@jkondrat can you please investigate further for those 3 providers?

**Comment by jkondrat** [comment] 2019-12-16 14:27
@bognasoldev89 @johnhbenetech : It looks that for Eden/UWBA/SMC we only have taxonomy codes and the names are empty. Should we display taxonomy codes in the dropdown?

**Comment by johnhbenetech** [comment] 2019-12-16 14:28
@jkondrat we should pull the names from the lookup tables and display those

**Comment by jkondrat** [comment] 2019-12-16 16:05
@johnhbenetech : I'm a little confused, where can I find these tables?

**Comment by johnhbenetech** [comment] 2019-12-16 17:43
@jkondrat 
the service_taxonomy joins to the taxonomy table. Taxonomy table has both external_db_id and name

**Comment by jkondrat** [comment] 2019-12-16 17:44
@johnhbenetech : The issue is that the name for these taxonomies is empty:
![Uploading Screenshot from 2019-12-16 18-44-04.png…]()

**Comment by johnhbenetech** [comment] 2019-12-16 18:14
@jkondrat I believe it's just that the taxonomy data jobs havent been run on development. I've kicked them off so hopefully the data will be there in a few minutes

**Comment by jkondrat** [comment] 2019-12-17 10:25
@johnhbenetech : Thank you, it worked!
@bognasoldev89 : Could you please have a look at these filters again? It turns out that after running taxonomy update jobs they are populated properly

**Comment by bognasoldev89** [comment] 2019-12-19 13:39
@jkondrat @johnhbenetech Taxonomy filters dropdown for Eden and UWBA providers are populated and working now.
SMCConnect still empty though :(
I saw that SMCConnect Taxonomy Update job was fired 3 days ago and taxonomy filter for this provider was empty. I fired it again today and still nothing.

![623 smc](https://user-images.githubusercontent.com/51324797/71177804-14904400-226d-11ea-9afa-68aaa2f44e13.gif)

**Comment by jkondrat** [comment] 2019-12-19 16:59
@bognasoldev89 : The filter only shows taxonomies that were actually used in record's services. I checked a couple of SMCConnect records, and their services either have no taxonomies, or taxonomy names are empty, that's why nothing is showing up in the filter. 
![Screenshot from 2019-12-19 17-49-01](https://user-images.githubusercontent.com/5969801/71192799-42838180-2289-11ea-9c90-8040d347cac9.png)

When I checked in the database it seems that only some of SMCConnect taxonomies have names:
![Screenshot from 2019-12-19 17-58-32](https://user-images.githubusercontent.com/5969801/71192778-3b5c7380-2289-11ea-8cb2-0699991e746b.png)

**Comment by johnhbenetech** [comment] 2019-12-19 17:29
Hmmm.. this isn't the case on prod so can we look at the SMC taxonomy job in dev?

**Comment by jkondrat** [comment] 2019-12-23 14:46
@johnhbenetech : The API (https://api.smc-connect.org/categories) does not return these taxonomies, is it possible that they were there before?
![Screenshot from 2019-12-23 15-44-16](https://user-images.githubusercontent.com/5969801/71364024-44a45380-259b-11ea-9a79-8b4d97012802.png)

**Comment by jkondrat** [comment] 2019-12-23 15:12
it turned out that there were duplicate taxonomies in the database (one with empty name), so I created a migration:
https://github.com/benetech/ServiceNet/pull/769

**Comment by bognasoldev89** [comment] 2020-01-08 13:32
Confirmed that taxonomy filter works for all providers now.

SMCConnect:
![623 smc working](https://user-images.githubusercontent.com/51324797/71981910-a9aaab00-3223-11ea-8be7-cdcf4de5e2f7.gif)

**Closed by bognasoldev89** 2020-01-08 13:32 UTC
Labels: PM: Search & Discovery, Priority A
