### ISSUE TITLE
When in Discovery mode, left column erroneously says "Your data"

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#733] opened 2019-11-19 15:40 UTC
When I search for resources with "Only include matching" deselected, then click on a search result not from my own database, then in the details view click to compare it to another partner, the record on the left erroneously says "Your data" when in fact it is coming from a partner system

Here I'm logged in as UWBAUser and you see I'm looking at a ShelterTech record compared to a HealthLeads record. The error is circled in the third screen shot.

![0](https://user-images.githubusercontent.com/52297301/69161278-c20e0d00-0a9f-11ea-8db0-1a651bdd2264.PNG)

![1](https://user-images.githubusercontent.com/52297301/69161305-cf2afc00-0a9f-11ea-91e6-d57f6aa01d8b.PNG)

![2](https://user-images.githubusercontent.com/52297301/69161323-d6eaa080-0a9f-11ea-9255-fbb78c9f238b.PNG)

**Comment by awalkowiak** [comment] 2019-11-20 11:13
@NeilMBenetech on which server you had this issue? Was it our staging instance? On staging for you search I have 2 results (one is the same as your uwba and other result from sheltertech has different name). When i opened ShelterTech record in side by side view is see the "From ShelterTech" label. Additionally I am a little bit concerned by 1/1 results number indicator on you first screenshot despite 3 results being displayed (on staging i have 2/2 which is correct with results displayed).

**Comment by NeilMBenetech** [comment] 2019-11-20 14:34
@awalkowiak I was on the production server at https://servicenet.benetech.org/#/

**Comment by johnhbenetech** [comment] 2019-11-20 14:36
I think this is a duplicate of #712 and has likely already been fixed in staging

**Comment by awalkowiak** [comment] 2019-11-21 10:31
@johnhbenetech @NeilMBenetech yup. It is fixed already on staging.

**Comment by johnhbenetech** [comment] 2019-12-17 14:44
@bognasoldev89 I think we've confirmed this is fixed, but I'll let you triple check :)

**Comment by bognasoldev89** [comment] 2019-12-19 13:46
@NeilMBenetech @johnhbenetech yes, I confirm it's ok :). I checked #712 during regression and did a quick exploration now - everything is fine.

**Closed by bognasoldev89** 2019-12-19 13:46 UTC
Labels: PM: Search & Discovery, Priority C, bug
