### ISSUE TITLE
Add an "import" button

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#404] opened 2019-05-01 00:08 UTC
- add an import button next to each non-empty field (on the partner's matching record).
>when users click on it, the text from the partner's field is automatically copied. (that way, the users can go to their own database and copy it directly)
>and it will enable us to track who has imported what more easily

**Comment by CloVasco** [comment] 2019-05-01 01:05
can be an arrow button. TBD

2 existing ideas - 
hit a button "import" button and it pastes for them (then they just need to paste) 
OR hit the import button and when the user is done, system generates a “report” with all the info that the user needs to paste in his/her database.  

 if they hit the button "import", the Service Net platform could automatically check if they didn’t paste and remind them.

**Comment by laurabenetech** [comment] 2019-05-06 19:41
@CloVasco Here is visual for import button next to field.  The screen could get pretty busy/cluttered if there are full-fledged buttons under the fields so suggested design here is simple clickable text under fields.

I don't know the technical side of the system checking and reminding them to paste: we'll need to check with @johnhbenetech  to see if that's technically feasible.

<img width="748" alt="Import button" src="https://user-images.githubusercontent.com/48697326/57250328-09e5af00-6ffc-11e9-84e8-05eb47b2fdd7.png">

**Comment by CloVasco** [comment] 2019-05-07 20:02
Thanks @laurabenetech . Something was bothering me when I looked at your visual for the first  time so I took more time to think about it and I chatted briefly with Alex this morning. Even if it’s not a full-fledged button, I am worried that this solution of adding text below each field (even if it’s fields with some content only) may be adding even more busyness to a page that we’re trying to make more appealing and simplified. 
How about adding a button between the left and right side with an arrow 
![image](https://user-images.githubusercontent.com/21065773/57329162-0b7ca900-70c8-11e9-9a2c-90f30798b28f.png)
 (and maybe with some text next to it or when you hover on it like “add” if I have no info or “update” if I already have some)? 

@johnhbenetech and @laurabenetech – what do you think?

@johnhbenetech – Two questions for you. 
-	Whatever the solution we end up choosing is, is it possible not to have this button appear for partners’ fields when they are empty?
-	Having the system remind them about the fact that they have not pasted is a nice-to-have but I don’t think it should be a priority if it takes a lot of time. Let me know and I can create a separate github item for this reminder feature to be done later.

**Comment by johnhbenetech** [comment] 2019-05-07 20:14
1. Yes we can hide if empty
2. It's not technically possible to detect if they have pasted, so we would need to take another approach.

**Comment by laurabenetech** [comment] 2019-05-07 20:44
@CloVasco You suggestion sounds fine for the arrow that displays "add" and update" when the user  hovers--let's go with that. And as John said, it won't appear when empty. 
@johnhbenetech do you need a visual or are Clotilde's instructions with the arrow visual above clear enough? Thanks, Laura

**Comment by CloVasco** [comment] 2019-05-10 00:52
Thanks @laurabenetech 
@johnhbenetech also suggested another option in terms of visual: 
![image](https://user-images.githubusercontent.com/21065773/57495312-6d810e00-7282-11e9-8c51-f4e7811cb824.png)  
with the idea that when you have clicked it, a message like "copied to clipboard" appears to tell you that you can now paste on your own platform.
@laurabenetech I'd like to know what you think between the two options

**Comment by laurabenetech** [comment] 2019-05-10 19:00
@CloVasco I really like the clear feedback of letting the user know that they’ve copied it to the clipboard, so that’s great to add that!
I’m guessing we wouldn’t use the Copy button though? Even if we’re hiding it when fields are empty it could still get pretty busy. 
So I'm guessing you mean that we'd use your idea of the arrow, with hover text of “Copy to clipboard” and once they click it, it would provide the feedback “Copied to clipboard”? Let me know if that's what you were thinking.

**Comment by laurabenetech** [comment] 2019-05-15 22:38
@CloVasco I met with John today about analytics planning. We agreed that including a copy button we can then track is key for understanding who is utilizing partner data, and how often they are. John said this is minimal work, development wise, so I suggest expediting this so that we can start tracking this important metric. Can this be moved up in the queue?

**Comment by johnhbenetech** [comment] 2019-05-24 21:36
@awalkowiak have you already started development on this? Can we please also tag this element with a google analytics event of "Copied Field" and also pass in the username as we have done with previous GA events?

**Comment by johnhbenetech** [comment] 2019-05-24 21:50
Also let me know what you think about this proposal:

* The button shouldn't appear on the single record view (because that's their own record)
* In side-by-side, the button should not appear on the user's own record (the one on the left in side-by-side view)
* The button should not appear on partner fields which are empty (since there is nothing to copy)
* The button should only appear when the user hovers over a partner field (let me know if this is annoying/difficult and we can talk about always displaying)
* Clicking the button logs google analytics event "Copied Field" with username dimension.

As far as UI:
* The button appears when the user hovers over any part of the field
* A tooltip appears when a user hovers over the button directly: "Copy to clipboard"
* After the user clicks the button, there is a small alert that says "Copied!"

![image](https://user-images.githubusercontent.com/12927553/58358291-ecaa4080-7e43-11e9-847e-e96023bbffb9.png)

I found this library, but it might be easier to do it natively:
https://www.npmjs.com/package/react-copy-to-clipboard

**Comment by awalkowiak** [comment] 2019-05-27 11:36
Hello @johnhbenetech, I started working on it (I was looking for/thinking about solutions). Your latest comment clarifies a lot, thanks for that. I also came across the same react component you linked (I use this one or I make my own if there will be need for it). Also, the hover on feature should be feasible.

**Comment by bognasoldev89** [comment] 2019-06-05 11:05
Hi @johnbenetech, "import" button works only on Firefox and Chrome, on Edge and Safari it's visible but it doesn't work. What do You think should be done about it? Should it be fixed now or issued in another ticket for later?

**Comment by johnhbenetech** [comment] 2019-06-05 11:25
@bognasoldev89 let's fix it as part of this task. We can move this task back to the top of up next column

**Comment by bognasoldev89** [comment] 2019-06-12 12:43
Confirmed that "import" works on Safari now, but still not on Edge.

**Comment by bognasoldev89** [comment] 2019-06-18 14:10
Now it's working on Edge but not on the latest Chrome (ver 75.0.3770.80)

**Comment by bognasoldev89** [comment] 2019-06-25 11:43
Confirmed that button works on four tested browsers.

**Closed by bognasoldev89** 2019-06-25 11:43 UTC
