### ISSUE TITLE
Search by wildcard in the free text box

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#639] opened 2019-08-20 23:53 UTC
Now that we have several different ways to filter, the user should be able to conduct a search that ignores the free text component of the search and returns all records that match the criteria set in the filters. This would allow them to discover records for which they may not know the name or alternate name. For example : Rent Payment Assistance (taxonomy) in Santa Clara County (geography).

Our choices for implementing this would be as follows, in my descending order of preference : 
1. If the search text box is empty, treat it as a "wildcard search" per above. Modify placeholder text by appending : "Leave blank to search all resource subject to the filters below."
2. If the user puts a special character into the search text box, such as an asterisk, treat it as a "wildcard search". Modify placeholder text by appending : "Type in an asterisk to search all resource subject to the filters below."
3. Add a check-box to the UI directly below the search text box that reads: "Return all records matching the filters below, without specifying text to search for."

A wildcard search should only be permitted to occur when at least two of the structured filters (geography, taxonomy, updated date, partner data source) are specified, so that an unmanageably large set of results is not returned. If this criteria is not met, please show the following error message: "To ensure your search returns a manageable quantity of results, please set at least 2 of the filters below."

**Comment by johnhbenetech** [comment] 2019-08-29 23:22
@NeilMBenetech I'm out on PTO until wednesday. Can you work with the team on this issue?
@jkondrat Can you @ Neil once this has been pushed to staging?

Neil per your definition above, a blank search bar is considered a wildcard. You also said a wildcard requires at least 2 filters. As a result on first load - no records show up, because the search box is empty and no filters have been set.

I'm not sure this was intended or a requirement gap. Please review and let the team know if you want to take a different approach

**Comment by NeilMBenetech** [comment] 2019-08-30 00:10
Thanks @johnhbenetech . I only realized today that a blank text box is a wildcard search. The "minimum two filters chosen" is simply to keep load down on the searches because I would assume every filter added, adds complexity to the database queries = slower. If that is not the case then we don't need the "minimum two filters". Then this simply becomes modifying the placeholder text by appending : "Leave blank to search all records." A little more concise than my initial suggestion. @jkondrat

**Comment by johnhbenetech** [comment] 2019-08-30 00:14
@neilmbenetech Can you leave a comment rewriting your three desired interactions from the original scoping with your updated thoughts. I'm still unclear on how blank, *, and minimum filters interplay

**Comment by NeilMBenetech** [comment] 2019-08-30 00:17
@johnhbenetech This fully collapses to simply this: Please append to the placeholder text in the search textbox the following phrase : "Leave blank to search all records."

**Comment by johnhbenetech** [comment] 2019-08-30 00:21
@neilmbenetech wasn't the impetus of this task allow for asterisk based searching?

Of your 3 original scoped pieces of work, both 2 and 3 required code changes above and beyond simply copy change.

Do you still want the ability to search by asterisk?

Do you still want the checkbox described in your point 3?

If you no longer want minimum filter requirements, should we undo all those code changes? Do you still want that requirement if a user uses an asterisk?

**Comment by bognasoldev89** [comment] 2019-09-03 13:24
I confirm that this issue with option 1 chosen works good, but I have to be honest, I am not entirely sure it is exactly what you wanted. I see a lot of unanswered questions and I want to be sure before closing this issue. The first load remains "empty" at this moment. @NeilMBenetech @johnhbenetech can you confirm, that option 1 from the first comment is the resolution for this issue?

**Comment by NeilMBenetech** [comment] 2019-09-03 17:03
@johnhbenetech and @bognasoldev89, sorry I thought I was clear in my last response. Yes I hadn't previously caught that a blank text box was a wildcard search so it is fine to leave it that way. I no longer see a need to require a minimum of 2 filters to be set if you don't think having just zero or one filter set is a performance challenge. And for both of these reasons we no longer need the checkbox.

**Comment by bognasoldev89** [comment] 2019-09-04 13:04
I'm moving this ticket back to "In progress" column to refine.

**Comment by johnhbenetech** [comment] 2019-09-04 16:06
Ok, it sounds like we should back out all this code. placeholders should be of the form:

"Search for organizations, leave blank to search all records"

**Comment by bognasoldev89** [comment] 2019-09-20 11:12
I think this issue just became this one: #625.
The first load shows a full list of records, one filter is enough to narrow down the search, information “To ensure your search returns a manageable quantity of results, please set at least 2 of the filters below” under search field is no longer visible.
Placeholder adjusts to Search for checkboxes (Organizations, Services and Locations)

Forms of placeholders after this issue:
![Screenshot from 2019-09-20 13-08-32](https://user-images.githubusercontent.com/51324797/65322891-48919580-dba8-11e9-9415-257c0c3298c4.png)

![Screenshot from 2019-09-20 13-08-49](https://user-images.githubusercontent.com/51324797/65322893-48919580-dba8-11e9-8458-ae335ab70b33.png)

![Screenshot from 2019-09-20 13-09-07](https://user-images.githubusercontent.com/51324797/65322894-492a2c00-dba8-11e9-8575-d2d4817c619d.png)

**Closed by bognasoldev89** 2019-09-20 11:12 UTC
Labels: DiscoverySearch
