### ISSUE TITLE
Make sure that the user experience is consistent across responsive views

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#984] opened 2020-05-12 15:37 UTC

**Comment by kkaczmarczyk** [comment] 2020-06-25 14:36
Tightly related  with #1065

**Comment by abaranowska1** [comment] 2020-08-03 11:07
@awalkowiak I looked into the UI and UX on mobile view and I have a few propositions which need improvement:

1. The right margin on the card view could be bigger ( it could be the same as left )
![Screenshot from 2020-08-03 11-05-05](https://user-images.githubusercontent.com/61964176/89175881-e4da4600-d588-11ea-83b3-a7da4840bef8.png)

2. These 3 buttons displayed on the edit view could have the same width or maybe you can change it to the pills buttons
![Selection_569](https://user-images.githubusercontent.com/61964176/89176111-3edb0b80-d589-11ea-8f94-ae352ec0924d.png)

3. After clicking the "Benetech" logo - the home page should be displayed as in the browser view
![logo](https://user-images.githubusercontent.com/61964176/89176244-7a75d580-d589-11ea-9d82-72b146bbc911.gif)

4. During testing the application on my iPhone X device I met one UI issue with the Location Details field - it is too high
![image](https://user-images.githubusercontent.com/61964176/89176336-a1cca280-d589-11ea-94a6-ee2335efa110.png)

5. @johnhbenetech I think about the "Back" buttons in the mobile view, do you think it's necessary or just the user can use the button on the phone?

**Comment by awalkowiak** [comment] 2020-08-03 13:13
@abaranowska1 thanks for your suggestions. I will fix mentioned issues. Regarding the back button: I think, that the phone's back button is enough and additionally there will be another option to go back to the home page after clicking the benetech logo. (cc @johnhbenetech)

**Comment by abaranowska1** [comment] 2020-08-10 11:21
@awalkowiak I retested all issues from the previous comment and I see that all points were done: 
- The right margin
- Buttons
- Moving to the homepage after clicking the logo
- UI issue 
- Long Organization Names

Now after changes to cards and pills buttons I noticed a few issues more: 

1. After zoom in the page, we can see UI issues on the cards, also pills are out of the card frame, and the left bar is too big.
![tempsnip](https://user-images.githubusercontent.com/61964176/89776257-cedd0000-db09-11ea-97cc-09ce50842f50.png)
![Przechwytywanie3](https://user-images.githubusercontent.com/61964176/89777437-fdf47100-db0b-11ea-8b0e-2227c817cf4b.PNG)

2. During testing on the Chrome Browser, I met UI issue with the progress bar ( missing pixel )
![Przechwytywanie7](https://user-images.githubusercontent.com/61964176/89776686-ab668500-db0a-11ea-8d9f-4c7d73676d95.PNG)
Chrome Browser on the left, Firefox browser on the right
![tempsnip3](https://user-images.githubusercontent.com/61964176/89776702-b0c3cf80-db0a-11ea-957b-2aa068eb9862.png)

3. If the Address or Organization name is very long and without spaces - UI issue exists, but I think that in real life such names without spaces will not exist cc @johnhbenetech 
![tempsnip1](https://user-images.githubusercontent.com/61964176/89777141-70188600-db0b-11ea-8df8-2d7ae9ca7439.png)

4. It is possible to add an empty card of location or service just after click Done button, but after clicking I'm Finished button we cannot save it - which is the expected result. Together with @awalkowiak, we decided that is it not a bug.

**Tested on:**
- Windows 10 OS
- Chrome v. Wersja 84.0.4147.105
- Firefox v. 79.0
- Mobile 360x640 and iPhone X

**Comment by abaranowska1** [comment] 2020-08-12 12:18
**Tested with success**

**Verified cases:**

- User Experience is consistent across responsive views 
- Buttons are changed to the pills buttons 
- Cards are in the right format 
- All issues from previous comments were fixed 

![image](https://user-images.githubusercontent.com/61964176/90013988-97f02100-dca6-11ea-807b-bc619eb83422.png)
![image](https://user-images.githubusercontent.com/61964176/90014007-9de60200-dca6-11ea-8baf-fe56b73146ac.png)
![image](https://user-images.githubusercontent.com/61964176/90014014-a2aab600-dca6-11ea-80f9-1671fb7c1cae.png)
![image](https://user-images.githubusercontent.com/61964176/90014026-a6d6d380-dca6-11ea-8729-8b9d3437601d.png)


**Tested on:**

- Ubuntu 18.04
- Chrome v. 84.0.4147.125
- Firefox v. 79.0
- Mobile 360x640 and iPhone X

**Closed by abaranowska1** 2020-08-12 12:18 UTC
Labels: ServiceProviderView, Story Points: 3, estimated, tech-debt-ideas
