### ISSUE TITLE
Confirm full functionality on stable platform

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#256] opened 2019-02-22 04:06 UTC
Ensure all partners FULL datasets can be loaded

Ensure organization matching completes successfully when ALL data from ALL partners have been added to the platform

Ensure conflicts are generated between ALL data from ALL partners

Ensure a user from each system account can log in and be presented with all conflicts for their records

**Comment by wojtekbu** [comment] 2019-02-22 21:25
Perspectives:

- A user with no provider - admin **OK**
- A user for every provider
  - Eden by job **OK**
  - Uwba by job **OK**
  - ShelterTech by job **OK**
  - LAAC by admin **OK**
  - Healthleads 2019-01-02 by admin **OK**
  - SMCConnect 2019-01-04 by admin **OK**

UI functionalities:
- Conflicts
  - Pagination **OK**
  - Sorting
    - By recommended **OK**
    - By recent **WRONG** → **fixed & ready to test on prod**
  - Detailed view **OK**
- User management
  - Activate user **OK**
  - Remove user **WRONG**
  - Update user **OK**
- User settings
  - Logging in **OK**
  - Logging out **OK**
  - Change password **OK**
  - Register **OK**
  - Update user info **OK**
- Upload data 
  - By admin **OK**
  - By user **WRONG**
- Scheduler **OK**

Total time ~4h (without localization matching) for all providers and with conflict detection. Eden and UWBA were fetched simultaneously and others one by one.

**Comment by johnhbenetech** [comment] 2019-02-22 21:32
@wojtekbu @oskarhinc Thanks for all the hard work on this. A few quick questions during my testing:

1. Re: data upload and fetching. Out of an abundance of caution I just did this one-by-one (while conflicts were being generated for previously uploaded sets). Beyond memory considerations is this a bad idea for screwing up conflict detection? Like once the data upload is completed, and two conflict detection processes are running. Is there any risk of them colliding or producing false duplicates? Or are all conflict detections added to a queue to be done in serial 

2. What is the logging for conflict detection. I've noticed an INFO log for each record being processed. I've also noticed some records take much longer than others to detect conflicts. Is this a result of the complexity of the record? Or does it only log once per source record (so a single log row could represent multiple comparisons to each partner record)?

**Comment by oskarhinc** [comment] 2019-02-23 10:19
1. When the organization import is finished, the algorithm starts to look for matching between all Organizations from different providers that are currently in the database and has no matches between them. After the match is found, looking for conflicts between two organizations is triggered automatically. So it's queue based but in memory. We've never encountered memory issues with this part of the application, but to minimize the risk we can either store the queue in the database, on creating a special job to refresh all conflicts between current matches. Does this answer your question, @johnhbenetech ?
2. The conflict detection is being executed only between organization matches, so the more matches are related to one organization, the more time it'll consume. As for now, we're only comparing basic organization information, so the record complexity should not affect the execution time. It logs only once for the organization, but it also logs, when the organization has no matches, so it won't be displayed on the home page anyway. We've added this logs to more easily found time-consuming parts of the application. We can display logs only for organizations that have matches, or if you don't want to see those, we can put them on the debug level, so it won't be visible on the production. Please let us know your preferences.

**Comment by oskarhinc** [comment] 2019-02-23 18:37
@johnhbenetech I've verified the memory usage today (as the location matching is already merged on the dev branch). I've uploaded data for LAAC, healthleads, and run the Eden fetching job. The memory usage has never exceeded 1GB, and no heap error was thrown. I was running it on the docker environment (with Postgres). 

We have optimized the location algorithm, so the memory usage is stable, and time is also reduced a lot, but due to the amount of data it still might take some time. We're now fetching the coordinates from the Google API right after the location is imported, so the matching algorithm is using them from the DB. Also, we're not asking Google API to count the distance between them, but we're counting it in Java, in the straight line, as it's much faster. However, for the development purposes, I've added the possibility to skip location matching for records that has 0.0 similarity ratio counted from other fields. I know that location is really important in the algorithm, so for the production, it's counted for each record, but if you would like to disable it, just change the flag 'similarity-ratio.config.location.always-compare' in application-prod.yml file. Of course, I've tested the data with full matching enabled, and before we merge it to the master we will be using the production setup, but it can speed up the whole process about ten times, so it might be useful for later tests.

We're going to update the master branch on Monday when the tests will be run once again after all changes, and we won't find any more issues.

**Comment by wojtekbu** [comment] 2019-02-25 15:05
Total time: (Eden & Uwba ~3.5h fetching and saving), stopped after 9h → all data was saved but conflict detection was taking too long
Uploading/fetching order: sequential ShelterTech → SMCConnect →Eden & Uwba →Healthleads →LAAC
Version: branch ‘dev’ commit ‘097e2555dbe227d27032effa41d8fb4151079c5c’
Additional info: Eden was triggered 30 min earlier than uwba; location similarity counter was enabled

Perspectives:

- A user with no provider - admin **OK**
- A user for every provider
  - Eden by job **OK** _but it couldn't connect with google api once_
  - Uwba by job **OK** _but no conflicts_
  - ShelterTech by job **OK**
  - LAAC by admin **OK** _but no conflicts_
  - Healthleads 2019-01-02 by admin **OK** _but no conflicts_
  - SMCConnect 2019-01-04 by user **OK**

UI functionalities:
- Conflicts
  - Pagination **OK**
  - Sorting
    - By recommended **OK**
    - By recent **OK**
  - Detailed view **OK**
- User management
  - Activate user **OK**
  - Remove user **WRONG** _in progress_
  - Update user **OK**
- User settings
  - Logging in **OK**
  - Logging out **OK**
  - Change password **OK**
  - Register **OK**
  - Update user info **OK**
- Upload data 
  - By admin **OK**
  - By user **OK**
- Scheduler **OK**

The larger data set system has the longer confflict detection took. After 8h (all data saved) the searching was taking even 30 min. It looks more like waiting for server response, but it could be also nonoptimal DB query.

**Comment by wojtekbu** [comment] 2019-02-25 15:26
@oskarhinc  here are the logs form last 4 hours:
```2019-02-24 18:26:33.936  INFO 8 --- [ XNIO-2 task-14] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for healthleads has started
2019-02-24 18:40:14.347  INFO 8 --- [ XNIO-2 task-18] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for LAAC has started
2019-02-24 18:44:24.468  INFO 8 --- [ XNIO-2 task-18] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for LAAC took: 250121ms
2019-02-24 18:45:36.104  INFO 8 --- [ XNIO-2 task-14] o.b.s.s.impl.DocumentUploadServiceImpl   : Data upload for healthleads took: 1142168ms
2019-02-24 18:57:27.156  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 0ms
2019-02-24 19:25:34.237  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 12ms
2019-02-24 19:25:34.306  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 28ms
2019-02-24 20:08:45.486  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 27ms
2019-02-24 20:46:42.936  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 0ms
2019-02-24 21:11:53.748  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 0ms
2019-02-24 21:55:39.146  INFO 8 --- [-net-Executor-1] o.b.s.c.ConflictDetectionServiceImpl     : Searching for conflicts took 0ms
```

**Comment by oskarhinc** [comment] 2019-02-25 15:35
@wojtekbu Thank's for the logs. The 'Searching for conflicts took [...]ms' log is displayed only when the match was found for an organization, and we compare them to find out their differences. So if there is 30 min between two logs it means that no matches were found during those 30 mins. Logs for matching are disabled for the production env as there's too many of them. I think we can disable those for conflicts as well as the conflicts detection is fast and stable now. 

According to 'no conflicts' in your report, are you sure the algorithm was finished? If it was running for 8h, with location comparison, and before https://github.com/benetech/ServiceNet/pull/278 is merged, I think the amount of compared orgs could be not enough to detect all conflicts, as the location comparison was time-consuming.

**Comment by wojtekbu** [comment] 2019-02-25 15:38
@oskarhinc the fetching/uploading and saving were finished for all providers. Matching and conflict detection was finished only for ShelterTech and SMCConnect. I guess the matching is a thing that we need to optimize now.

**Comment by oskarhinc** [comment] 2019-02-25 15:51
@wojtekbu let me know if those performance issues are still visible with the newest changes. I think there always be a place for optimization, but except for not running parts of the algorithm when there probably won't be a match anyway, the changes we can make won't probably speed it up a lot. I think we need to have detailed info about the execution time and let John decide if we should still focus on the optimization.

**Comment by wojtekbu** [comment] 2019-02-26 18:08
@johnhbenetech @oskarhinc @pgesek 
Total time: upload&save&location 3h; matching/conflicts result are visible right away but total time is more like a ~9h
Uploading/fetching order: sequential ShelterTech → SMCConnect → LAAC → Eden & Uwba →Healthleads 
Version: branch ‘dev’ commit 9f6c0d9ecc7dc4e7e416c0e680d5d99dc32b5c8f’
Additional info: upload is fine, but conflicts are constantly appearing for much longer period

Perspectives:

- A user with no provider - admin **OK**
- A user for every provider
  - Eden by job **OK** _but it couldn't connect with google api once_
  - Uwba by job **OK**
  - ShelterTech by job **OK**
  - LAAC by user **OK**
  - Healthleads 2019-01-02 by user **OK**
  - SMCConnect 2019-01-04 by admin **OK**

UI functionalities:
- Conflicts
  - Pagination **OK**
  - Sorting
    - By recommended **OK**
    - By recent **OK**
  - Detailed view **OK**
- User management
  - Activate user **OK**
  - Remove user **WRONG** _ready to test on dev_
  - Update user **OK**
- User settings
  - Logging in **OK**
  - Logging out **OK**
  - Change password **OK**
  - Register **OK**
  - Update user info **OK**
- Upload data 
  - By admin **OK**
  - By user **OK**
- Scheduler **OK**

**Comment by johnhbenetech** [comment] 2019-02-28 20:06
@wojtekbu @oskarhinc 
Can you clarify the Additional Info comment. I've been trying to test the latest with location improvements but I keep running into the following:

Uploading data goes fine, entities are created.
Organizational matching seems to be functioning, seeing ~300+ matches

Saw some conflict messages in log early on, confirmed ~30 conflict entities created in the first 10 minutes. Following that for the next 4 hours no additional conflicts were created.

Is this expected? Assuming there is more that 30 conflicts.

**Comment by johnhbenetech** [comment] 2019-03-01 00:06
@wojtekbu @oskarhinc Just an update from my side. I waited a few more hours then killed it. Nuked that instance and started fresh (I upped the JVM max heap too). After org matching finished, this time it got up to ~35 conflicts in 10 minutes then stopped, no new conflicts over the next 4 hours. Started fresh again.

We had a user test today (I wanted to test search and the new side-by-side view) so i ran the new instance with similarity-ratio.config.location.always-compare set to false as you suggested. Org matching functioned well, after that conflict detection functioned as expected,  conflicts were added one by one over the course of several hours (multiple conflicts being detected per minute).

The matches were a bit wonky at times, but it provided a decent test for users. 

It seems to me that the new location comparison is running into some issues. I tried to monitor memory usage but didnt see anything crazy. Not sure what the issue could be.

**Comment by oskarhinc** [comment] 2019-03-01 07:19
@johnhbenetech It definitely should not happen that two executions of the same workflow gave you different results. Could you provide us steps to reproduce this and some additional info (was the data updated simultaneusly, in which order, did the import for the first provider finished before updating the second one, JVM max heap, was the schedule job running during the import)?

**Closed** 2019-04-18 14:34 UTC
