### ISSUE TITLE
Fix size of fields

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#372] opened 2019-04-06 01:30 UTC
To make sure user can easily read what's in a field. Arantxa told Clotilde about this problem during my end-of -March call + we saw this during our training:
sometimes the text is super long, the size of the box is too small and it's not possible to drag the box down to make it bigger (for instance, not possible to do for the eligibility field)

1-	Make the description field bigger + edit name of Description field “Description (To expand: click and drag lower right corner)”
2-	Increase the size of other fields as well when needed + enable to expand the box for **all** other fields and make them scrollable whenever it is not big enough

_Next Step_: john to generate stats on average/median length of all fields to determine which ones need fixing

**Comment by johnhbenetech** [comment] 2019-04-16 21:57
@CloVasco is this a duplicate of #378

**Comment by johnhbenetech** [comment] 2020-09-18 16:39
Closing this as obsolete

**Closed by johnhbenetech** 2020-09-18 16:39 UTC
