### ISSUE TITLE
CSV Upload of phone numbers

### ISSUE THREAD

**Issue by jkondrat** [benetech/ServiceNet#1240] opened 2020-09-17 10:40 UTC
Once #1239 is done, add a possibility to upload a csv with a list of phone numbers and dates

**Comment by johnhbenetech** [comment] 2020-09-17 13:58
@jkondrat I think all 'bulk' action related tasks will be pulled back for additional scoping considerations.

**Comment by johnhbenetech** [comment] 2020-09-17 13:59
Possible duplicate of #1209

**Closed** 2020-11-24 15:57 UTC
Labels: Story Points: 5, estimated
