### ISSUE TITLE
Improve URL conflict detection

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#475] opened 2019-06-05 15:42 UTC
Currently conflicts are logged for URL even when there are no meaningful differences between values - such as:

* http vs no http
* www vs no www
* http vs https
* trailing / vs no trailing /

Make URL conflict detection smarter so it only detects meaningful difference.

For right now we should still log a conflict for different directory/pages on the same domain, e.g.:
* google.com vs google.com/page.html
* google.com/dir vs google.com/example

**Comment by awalkowiak** [comment] 2019-06-05 15:50
Dev note: Wwe could use regex groups to cleanup site and compare only that part

**Comment by bognasoldev89** [comment] 2019-06-14 13:32
Unfortunately, this issue needs more work, I found a few examples like this one:
![Uploading Screenshot from 2019-06-14 14-46-00.png…]()

**Comment by pmuchowski** [comment] 2019-06-14 13:49
@bognasoldev89 did you uploaded this organization or just looked through the existing records?
I'm not sure if you aware of this, but you need to update an organization for it's conflicts to be updated. There might still exist some old incorrect URL conflicts, because those was detected before this code was merged.

**Comment by bognasoldev89** [comment] 2019-06-14 13:52
@pmuchowski I was not aware actually, I am gonna check it further then. Thanks for the advice.

**Comment by bognasoldev89** [comment] 2019-06-17 14:53
After uploading data I've found that after uploading data as Healthleads (differences mentioned in the first comment) the app still sees conflicts. I've also tried ShelterTech data and I've found that some of these works (Trauma Recovery Center).

**Comment by bognasoldev89** [comment] 2019-07-03 09:36
Confirmed that URL conflict detection is improved  and ignores not meaningful differences between values

**Comment by kkaczmarczyk** [comment] 2019-07-03 16:08
The solution is not null-safe. Moving ticket back.

![image](https://user-images.githubusercontent.com/3207119/60607393-77744880-9dbd-11e9-944c-84a69d7a3d40.png)

**Comment by kkaczmarczyk** [comment] 2019-07-04 16:30
@mariaogryczak make sure to include a test for null case please.

**Comment by bognasoldev89** [comment] 2019-07-22 14:38
Confirmed that URL conflict detection is improved, ignores not meaningful differences between values and is null-safe.

**Closed by bognasoldev89** 2019-07-22 14:38 UTC
