### ISSUE TITLE
Matching and Discovery algorithm is inconsistent

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#732] opened 2019-11-19 15:35 UTC
As pointed out by Edward Wang at ShelterTech, the matching algorithm seems to be inconsistent. Please see the Google Doc he created with screen shots for an example where SN is matching differently for the same search types.

https://docs.google.com/document/d/1z44potwY-Ovj8yP2InqzJrJCpObDbNYKbq-BGxpG1SE/edit

**Comment by awalkowiak** [comment] 2020-01-09 13:11
@NeilMBenetech @johnhbenetech 

I tried to reproduce the issue from doc on staging and local environment.

**Staging**: It seems like it works properly (all available and expected data was shown for cases mentioned in the doc). Have anyone of you encountered similar issue to the mentioned one on staging recently? 
**Locally**: I found sort of similar case. When I searched for 'haight ashbury' (search fields: name, Only show matching: unchecked) - I got 3 results: one from UWBA (conflicting with ShelterTech), one from ShelterTech (conflicting with UWBA) and one from SMCConnect (conflicting with Healthleads). No result from healthleads was visible on the record list. When I opened the last displayed record I saw, that Healthleads organization record had completely different name. Hence it was not shown on home page results, because we filter results in the end by the name entered in search box. So this result was expected and works fine. (You can check this behavior on staging when searching for "SELF-HELP", while having UWBA System account - note: it is partial term, not selected from the list)

It looks like Edward spotted this behavior either on older code base (I assume it was on production or on older staging version) or on database with some redundant data (staging database was cleaned up couple of times). Perhaps recent similarity feature improvements fixed this issue. @johnhbenetech do you have any plans related to doing release on production? 
If you spot similar issues on staging please let me know and I investigate further this problem.

**Comment by NeilMBenetech** [comment] 2020-01-09 19:33
@awalkowiak Could you also test this on production?

**Comment by awalkowiak** [comment] 2020-01-10 10:22
@NeilMBenetech I checked it on current production. Everything is looking fine. The missing UWBA record for 'haight ashbury' is present and visible on the record list. I'm assuming that the issue which Edward found was related to older code base and is not valid anymore.

**Comment by awalkowiak** [comment] 2020-01-10 16:07
@NeilMBenetech Can I close this issue and move it to done?

**Comment by NeilMBenetech** [comment] 2020-01-12 19:13
@awalkowiak Looks good to me.

**Closed** 2020-01-12 21:10 UTC
Labels: PM: Search & Discovery, Priority B, bug
