### ISSUE TITLE
Create single record view

### ISSUE THREAD

**Issue by johnhbenetech** [benetech/ServiceNet#12] opened 2018-11-08 06:48 UTC
Placeholder parent task for the single-record view a logged in user gets when clicking on a single row in the list view.

More detailed tasks will be added for conflict resolution UI, side panel activity view, side by side record view, etc

**Comment by johnhbenetech** [comment] 2018-11-13 22:13
Putting mockup for ease. Fields should be read only at first. This should display the original parent record (from the logged in user) and then should suggest the normalized version of matching records for our limited set of fields we can match on.

![image](https://user-images.githubusercontent.com/12927553/48446414-c867fb80-e75e-11e8-9ed0-091dd7a03107.png)

**Comment by oskarhinc** [comment] 2019-01-17 12:38
Duplicate of https://github.com/benetech/ServiceNet/issues/23

**Closed by oskarhinc** 2019-01-17 12:38 UTC
