### ISSUE TITLE
Enhance search feature - category

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#297] opened 2019-03-16 01:16 UTC
enable users to search by:
-category - food, homelessness

Question - should be through search or filter??
-How to use taxonomy?
-Which list should we use - they can use an unlimited list or we give them a specific list?

**Comment by NeilMBenetech** [comment] 2019-07-11 17:19
Hi @CloVasco , can this one be closed/discarded because it is a duplicate of this one https://github.com/benetech/ServiceNet/issues/531 , which has more detail in it?

**Comment by CloVasco** [comment] 2019-07-16 00:19
@NeilMBenetech yes. you are right

**Comment by NeilMBenetech** [comment] 2019-07-16 21:07
Closed as a duplicate.

**Closed by NeilMBenetech** 2019-07-16 21:07 UTC
Labels: DiscoverySearch
