### ISSUE TITLE
URL conflict detection is not working as expected

### ISSUE THREAD

**Issue by abaranowska1** [benetech/ServiceNet#902] opened 2020-04-01 12:11 UTC
Currently conflicts are logged for URL even when there are no meaningful differences between values 
For example: 
1. Here we shouldn't have a conflict 
![Selection_102](https://user-images.githubusercontent.com/61964176/78136169-7727dd00-7423-11ea-8a11-91033ff67566.png)
![Screenshot from 2020-04-01 13-49-40](https://user-images.githubusercontent.com/61964176/78136187-7e4eeb00-7423-11ea-82b1-a67f3af0606c.png)
2. Here we should have a conflict 
![image](https://user-images.githubusercontent.com/61964176/78139112-4a29f900-7428-11ea-8557-9c9ed72610f1.png)

Expected result: Conflicts should be displayed as in desc from #475 
Similar issue : #799

**Comment by kdondziak** [comment] 2020-04-09 14:26
@johnhbenetech The issue was caused by some misunderstanding. When uploading data via 'upload data' user my have experience, that after getting success message after clicking upload button, all data are updated. That is true regarding data like organization name, url, but not matches/conflicts. Updating matches/conflicts may take up to couple of minutes. Our suggestion is to add some indicator that informs user that computing matches and other data are in progress or is complete.

**Comment by kkaczmarczyk** [comment] 2020-04-09 19:50
@kdondziak @johnhbenetech yeah I agree we can consider some kind of progress indication along with spitting out the task/job/compute microservices, though this may not be high priority.

@abaranowska1 can you confirm that the conflict appeared after some time? if so, I think we can close this ticket, and keep an eye for it in future regression tests.

**Comment by abaranowska1** [comment] 2020-04-10 06:51
I confirm that conflict appeared after a few minutes ( 5min ) after upload data. 
Just after upload data:
![833](https://user-images.githubusercontent.com/61964176/78969746-03af5b00-7b08-11ea-9c7e-317c5bafaf94.gif)
After 5 minutes after upload data:
![839](https://user-images.githubusercontent.com/61964176/78969787-1b86df00-7b08-11ea-8d21-45c85072fa90.gif)

**Closed** 2020-04-10 06:51 UTC
Labels: Story Points: 2, bug
