### ISSUE TITLE
Filter search results by timeframe of last updated date

### ISSUE THREAD

**Issue by CloVasco** [benetech/ServiceNet#301] opened 2019-03-16 01:26 UTC
Enable users to filter by:
-timeframe of updates (last week/last month.. for instance), 
-Address (+ add distance based - within X miles of zipcode/city/county/address) ?

**Comment by NeilMBenetech** [comment] 2019-07-11 17:17
I'm going to refine this one just to focus on the timeframe. I've also refined https://github.com/benetech/ServiceNet/issues/357 to focus on filtering/sorting by address/location.

So this one now becomes : 
Enable users to filter search results by timeframe of last updated date, and choose to sort in chronological or reverse-chronological order.
User should be able to choose timeframes from a dropdown list : This week, Last week, This month, Last month. They should also be able to supply a beginning and ending date with two datepickers, and the filtering will be inclusive of selected dates. UI validation to ensure beginning date is before ending date.

**Comment by johnhbenetech** [comment] 2019-07-30 14:31
Per call. For the dropdown lets start with: Last 7 Days, Last 30 Days

**Comment by bognasoldev89** [comment] 2019-08-01 11:28
Confirmed that filtering feature designed for timeframe works as it is supposed to work.

![Screenshot from 2019-08-01 13-26-17](https://user-images.githubusercontent.com/51324797/62289838-11342180-b460-11e9-8bb7-875195fa19c4.png)

**Closed by bognasoldev89** 2019-08-01 11:28 UTC
Labels: DiscoverySearch

**Comment by NeilMBenetech** [comment] 2019-08-17 22:07
@johnhbenetech Seems to be working with some minor feedback. 1. Please have calendar popups on date pickers, unless you feel strongly the current "up/down" arrows are better. 2. Prevent the "from" date from being later than the "until" date. 3. Appears to correctly be working on the targeted record type (Organization, Service, Location), not just Organization, which is great. Hard / laborious to confirm though - however search results are different when I target different record types with otherwise the same search, so it's probably working properly.

**Comment by johnhbenetech** [comment] 2019-08-19 19:26
For 1, Are you using safari by chance? We have #608 to deal with that. Should work in other browsers.

2. Can you break out a separate task for that (unless you think this is a release blocking requirement)

**Comment by NeilMBenetech** [comment] 2019-08-20 23:27
@johnhbenetech 
I was using Chrome on Windows.
I'll add new task for from/until validation. It was specified in my July 11 req's on this task but no need to have it block the deployment.
