### ISSUE TITLE
CBO Service Net Referral Tracking Database Initial Idea 

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1176] opened 2020-09-02 19:38 UTC
- Have a database for each beneficiary
- track: where it was referred from with a timestamp, where it was referred to, and if the unique identifier or phone number gets inputted in their system then mark as a successful referral with a timestamp

<img width="465" alt="Annotation 2020-09-02 123639" src="https://user-images.githubusercontent.com/65787629/92028529-0a3da980-ed19-11ea-8112-23ef96b4ed87.png">

**Comment by johnhbenetech** [comment] 2020-09-08 15:12
I'd probably recommend we make two new entities: Referral and Beneficiary

Beneficiary:
* UUID
* Phone number (if collected)
* Any other columns you can think of? By having a separate table we can always add new info as we discover we need to collect it.

Referral:
* UUID
* Beneficiary UUID
* OrganizationID for referred from org
* OrganizationID for referred to org
* Shortcode 
* Referral sent datetime
* Referral fulfilled datetime

So if 'referral fulfilled' in null, we can infer the beneficiary didn't receive the referred to service or the service provider neglected to use the id to close the loop.

**Comment by kkaczmarczyk** [comment] 2020-09-16 10:05
@johnhbenetech considering db design - the field '**OrganizationID for referred from org**' shouldn't this be UserID or SiloID considering the behavior described in #1173? If not how this field should be inferred?

**Comment by EnriqueCorado** [comment] 2020-09-16 14:25
We want to have different attributes, one to distinguish the organization a place is referring to and the other one to recognize where the referrals are coming from 

Referral:

UUID
Beneficiary UUID
OrganizationID (org ID referred to)
OrganizationID (org ID receiving references from) 
Shortcode
Referral sent datetime
Referral fulfilled datetime

let me know if that makes a little more sense @kkaczmarczyk

**Comment by johnhbenetech** [comment] 2020-09-16 14:51
@EnriqueCorado The problem is that there isnt a 1:1 mapping between logged in user and the "from" organzation. A single logged in user may be the 'owner' of multiple CBO records. A single CBO record may be managed by multiple users.

So the two options I see (I'm sure there are more):

* We just have the "from" being a UserID and the "to" is the OrganizationID. We won't know exactly where the referral originated, only the user who originated it.

* We add a dropdown in the referral flow where the user has to select which of their 'owned' records they are acting on behalf of. There are more details needed here as far as UI mockups as well as is this selected on a 'cart' basis or on each referral

**Comment by EnriqueCorado** [comment] 2020-09-16 18:36
- add a dropdown as below on the referral page if they have multiple records
- if only one record, look at the last two screenshots 



**Desktop View**
<img width="734" alt="Screenshot 2020-09-16 112351" src="https://user-images.githubusercontent.com/65787629/93376932-2d835100-f80f-11ea-8499-d51331b5553d.png">


<img width="760" alt="Screenshot 2020-09-16 112403" src="https://user-images.githubusercontent.com/65787629/93376937-307e4180-f80f-11ea-89fb-726f8a058605.png">

**Mobile View**

<img width="203" alt="Screenshot 2020-09-16 113058" src="https://user-images.githubusercontent.com/65787629/93377654-2872d180-f810-11ea-84bf-e8730cc5a1a7.png">


<img width="191" alt="Screenshot 2020-09-16 113150" src="https://user-images.githubusercontent.com/65787629/93377700-3cb6ce80-f810-11ea-97b7-6c512fb31d07.png">


**if only one record keep this layout on referral page ** 
<img width="206" alt="Screenshot 2020-09-16 113508" src="https://user-images.githubusercontent.com/65787629/93378120-d3838b00-f810-11ea-87c5-cad4778f6e62.png">
<img width="253" alt="Screenshot 2020-09-16 113438" src="https://user-images.githubusercontent.com/65787629/93378127-d54d4e80-f810-11ea-8995-c904699119db.png">

**Comment by johnhbenetech** [comment] 2020-10-01 17:43
We can break this out into a separate task, but something occurred to me as I thought through this a bit more. I think there may be one gap we should discuss @EnriqueCorado 

Is it a safe assumption that we not only want to refer someone to a specific Org but ALSO a specific location within that Org? Is that true? I'm imagining a hopefully rare case where an org has 50 locations. In the SMS - I think it would be hard to shove so much stuff in there.

What do you think?

This would impact the schema since we'd need to add the location ID, but also would impact what happens when the 'Refer' button is hit. If there is only one location in the org we can make that association automatically, but if there are lots of locations we kinda need the partner to potentially tell us which location they are sending to. The other option is just to wait and see where the beneficiary shows up, and ask the location on the check-in side - then as part of closing out the referral we fill in the location ID,

**Comment by EnriqueCorado** [comment] 2020-10-01 18:48
@johnhbenetech 

It is true we want to refer to a specific org but also a specific location(s). I'm assuming an organization won't have more than 2 or 3 locations max in a city. Which then those 3 locations could serve as options to the beneficiary. 

From the initial referral standpoint, the user will specify the city or distance from their CBO they are referring from. So that would filter the locations not within those boundaries. What I'm trying to say is when a CBO is referring to another CBO, and the beneficiary wants a Food Pantry in the same city (Palo Alto) all the locations of that organization they are referring to outside Palo Alto wouldn't show. 

This is something we can add to the schema, but to automatically filter the locations of that organization out of the boundary specified to keep the referees task simple

**Comment by johnhbenetech** [comment] 2020-10-01 19:00
@EnriqueCorado Can you split this out into a separate task. I think there are more things to figure out here. mainly:

* How do we know what city they are in currently (so that we can do any sort of filtering). Even if we tried to do something with the browser location info there are plenty of cases where that will be denied or very inaccurate. 

* "From the initial referral standpoint, the user will specify the city or distance from their CBO they are referring from" - that's not currently in any task definition that I know of. Right now a referral can be made to any organization using the button on the card.

If we need more time to figure these things out, or need significant changes to the approach (which it sounds like we will need) I'd encourage us to start with an MVP that is at least testable even if it isnt most efficient. The most obvious options I see are:

1. Keep as it is right now. Referrals are to the general organization.

2.  If only one location is attached we can send that info. If there is more than one location we can send a link to the public view of the organization record (if the record is in a public silo)

3. At the point of referral or at the point of check in, the CBO worker needs to select the location from a dropdown before they are allowed to finish that process. If there are 0 or 1 locations - this will be done automatically. For more than 1 we will list all options. In the future we can improve the sorting of the locations based on some other info (distance or whatever), prepopulate with the last location used if available, or we can allow some setting like 'always use this location'

Please decide on an MVP solution and make a separate task. Then you can also break out a task for a more future-looking improvement

**Comment by abaranowska1** [comment] 2020-10-05 13:17
@jkondrat I found some issues:
1. Missing translations after creation Beneficiary and Referral
![image](https://user-images.githubusercontent.com/61964176/95081422-d1c72c00-0719-11eb-9f4c-fff07b910793.png)
![image](https://user-images.githubusercontent.com/61964176/95081437-d5f34980-0719-11eb-973b-f3511e2562f9.png)

2. After create, edit, delete Beneficiary / Referral we are always moving to the homepage - users should stay on the Beneficiary / Referral page after doing one of this action
![Peek 2020-10-05 14-28](https://user-images.githubusercontent.com/61964176/95081981-a98bfd00-071a-11eb-9f7a-e4775e0703fd.gif)

3. On the Referral edit or create page Beneficiary ID is displayed on dropdowns which I think is unreadable 
![image](https://user-images.githubusercontent.com/61964176/95082512-6d0cd100-071b-11eb-84fd-0a9aefbc32f3.png)

4. Internal Server Error is displayed when I try to delete Beneficiary which I use to Referral 
![Peek 2020-10-05 15-06](https://user-images.githubusercontent.com/61964176/95083172-6c286f00-071c-11eb-93b7-01087947380b.gif)

5. On the Referral edit or create page issue #1228 also exist. It limits us picking the right Organization.

**Comment by abaranowska1** [comment] 2020-10-07 13:15
**Tested with success**
- Missing translations were added 
![image](https://user-images.githubusercontent.com/61964176/95334940-09b3a800-08af-11eb-92bf-68087e3f4c9b.png)
![image](https://user-images.githubusercontent.com/61964176/95334952-0c160200-08af-11eb-9eb1-cf8b33e42bc6.png)
- After create, edit, delete Beneficiary / Referral we stay on the Beneficiary / Referral page 
- Besides the id there is also a phone number
![Uploading image.png…]()
- It is possible to delete Beneficiary which I use to Referral
![Peek 2020-10-07 13-59](https://user-images.githubusercontent.com/61964176/95335460-b4c46180-08af-11eb-9627-21a161d353ee.gif)

**Closed** 2020-10-07 13:18 UTC
Labels: Story Points: 2, estimated
