### ISSUE TITLE
Issues with Search - using Taxonomy and Geography filters together

### ISSUE THREAD

**Issue by NeilMBenetech** [benetech/ServiceNet#661] opened 2019-08-28 21:49 UTC
When I set the fields with Taxonomy = Food Pantries and click apply, I get 25 results, the first one being the "San Francisco - Marin Food Bank" (which has multiple locations in both the city of San Francisco and the county of Marin. If I add a geographic filter either for City of San Francisco, County of San Francisco, or County of Marin, and hit Apply Filters, I get no results returned.

The same issue occurs with Taxonomy = Personal Finance Counseling and County = San Francisco. The Organization "Sparkpoint San Francisco" https://benetechservicenet.org/#/single-record-view/44d2d533-76ff-4dd6-83b1-ae315a8c8a98 is my top search result when I specify just the Taxonomy, but I get no results if I specify the City = San Francisco or the County = San Francisco. I confirmed the record does have a Location record in both the City and County of San Francisco.

**Comment by johnhbenetech** [comment] 2019-08-28 22:26
@bognasoldev89 Can you look into this?

**Comment by bognasoldev89** [comment] 2019-08-29 07:25
> @bognasoldev89 Can you look into this?

Of course.

**Comment by bognasoldev89** [comment] 2019-08-29 14:44
@NeilMBenetech @johnhbenetech I reproduced those steps and Taxonomy filter is irrelevant in this issue.
I'm moving this ticket to Up next column and I believe @kkaczmarczyk will look into it.

**Comment by kkaczmarczyk** [comment] 2019-09-20 16:00
I have investigated this a bit - seems like sometimes the relation between location and geocoding result is not being saved ('location_geocoding_results' db table) at times. 
The records in geocoding_results are being saved properly. This may be related with server restarts before letting the organization import finish. If that's a case, there should be some fall-back mechanism.
@jkondrat Can you investigate further?

**Comment by bognasoldev89** [comment] 2019-10-17 12:38
I checked Neil's cases and did some digging by myself and it looks like functionality works fine now.

Screenshots from cases provided by Neil:

![Screenshot from 2019-10-17 14-34-15](https://user-images.githubusercontent.com/51324797/67009348-bb305b00-f0eb-11e9-8439-6b2e4ad0cea1.png)

![Screenshot from 2019-10-17 14-34-46](https://user-images.githubusercontent.com/51324797/67009349-bb305b00-f0eb-11e9-878e-13cd4413f1e2.png)

**Closed by bognasoldev89** 2019-10-17 12:38 UTC
Labels: DiscoverySearch
